### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by JannikStreek** [ScrapingAnt/aws-lambda-docker-research#1]
Hi!

great blog article. Can you maybe add a license so it's safe to work with the code?

Best regards!

**Comment by kami4ka** [comment]
@JannikStreek sure. Thanks for noticing it.
@megabotan could you please take a look?

**Comment by JannikStreek** [comment]
that would be great thanks! MIT would be nice (and I think that's the intention with the blog) but the choice is obviously up to you :)
